"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-07-05 10:18:13.996205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('x1', sa.Float(), nullable=True),
    sa.Column('y1', sa.Float(), nullable=True),
    sa.Column('x2', sa.Float(), nullable=True),
    sa.Column('y2', sa.Float(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('stream_id', sa.String(), nullable=True),
    sa.Column('inference_time_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detections_frame_id'), ['frame_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_stream_id'), ['stream_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_track_id'), ['track_id'], unique=False)

    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('stream_id', sa.String(), nullable=True),
    sa.Column('inference_time_ms', sa.Float(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('num_detections', sa.Integer(), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('memory_mb', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metrics_stream_id'), ['stream_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metrics_timestamp'), ['timestamp'], unique=False)

    op.create_table('stream_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('tracking_enabled', sa.Boolean(), nullable=True),
    sa.Column('total_frames', sa.Integer(), nullable=True),
    sa.Column('total_detections', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stream_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stream_sessions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_stream_sessions_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stream_sessions_stream_id'), ['stream_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stream_sessions_stream_id'))
        batch_op.drop_index(batch_op.f('ix_stream_sessions_started_at'))
        batch_op.drop_index(batch_op.f('ix_stream_sessions_is_active'))

    op.drop_table('stream_sessions')
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metrics_timestamp'))
        batch_op.drop_index(batch_op.f('ix_metrics_stream_id'))

    op.drop_table('metrics')
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detections_track_id'))
        batch_op.drop_index(batch_op.f('ix_detections_timestamp'))
        batch_op.drop_index(batch_op.f('ix_detections_stream_id'))
        batch_op.drop_index(batch_op.f('ix_detections_frame_id'))

    op.drop_table('detections')
    # ### end Alembic commands ###
