apiVersion: v1
kind: Service
metadata:
  name: omnitrack-backend
  namespace: omnitrack
  labels:
    app.kubernetes.io/name: omnitrack
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: omnitrack
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
