apiVersion: v1
kind: Service
metadata:
  name: omnitrack-frontend
  namespace: omnitrack
  labels:
    app.kubernetes.io/name: omnitrack
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: omnitrack
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
